export const COLORS_LIGHT_DARK = '#595D6E';
export const COLORS_LIGHT_DARK_ALPHA = '#595D6E96';
export const COLORS_ALPHA_LIGHT_DARK = 'rgb(139, 142, 154)';
export const COLORS_DEFAULT_LIGHT = '#E5E5E5';
export const COLORS_DEFAULT_ALPHA_LIGHT = '#E5E5E587';
export const COLORS_LIGHTER = '#F5F5F5';
export const COLORS_LIGHT_BLACK = '#272727';
export const COLORS_PRETTY_BLUE = '#00609F';
export const COLORS_PRETTY_GREY = '#E4E8EE';
export const COLORS_PRETTY_GREY_DARK = '#CBD3DE';
export const COLORS_LIGHT_RED = 'rgb(255, 88, 88)';
export const COLORS_DEFAULT_LIGHT_RED = '#ffa1a1';
export const COLORS_DEFAULT_DARK_RED = '#ff4f4f';
export const COLORS_DARK_GREEN = '#212529';
export const COLORS_DARK_GREEN_ALPHA = '#343a40';
export const COLORS_DARK_GREEN_LIGHT = '#545b63';
export const COLORS_LIGHT_GREEN = '#bafc00';
export const COLORS_DEFAULT_LIGHT_BLUE = '#81d4fa';
export const COLORS_DEFAULT_DARK_BLUE = '#03a9f4';

export const NOBBLE_DEFAULT_COLORS = [
  COLORS_LIGHTER,
  'WHITE',
  COLORS_LIGHT_DARK,
  COLORS_DARK_GREEN,
  COLORS_PRETTY_GREY_DARK,
  COLORS_DARK_GREEN_LIGHT,
  COLORS_PRETTY_BLUE,
  COLORS_PRETTY_GREY,
  COLORS_ALPHA_LIGHT_DARK,
  COLORS_LIGHT_RED,
  COLORS_DARK_GREEN_LIGHT,
];
